Traceback (most recent call last):
  File "run.py", line 215, in <module>
    main()
  File "run.py", line 208, in main
    trials=trials)
  File "/Users/katya/venv/lib/python2.7/site-packages/hyperopt-0.0.2-py2.7.egg/hyperopt/fmin.py", line 334, in fmin
  File "/Users/katya/venv/lib/python2.7/site-packages/hyperopt-0.0.2-py2.7.egg/hyperopt/fmin.py", line 294, in exhaust
  File "/Users/katya/venv/lib/python2.7/site-packages/hyperopt-0.0.2-py2.7.egg/hyperopt/fmin.py", line 268, in run
  File "/Users/katya/venv/lib/python2.7/site-packages/hyperopt-0.0.2-py2.7.egg/hyperopt/fmin.py", line 187, in serial_evaluate
  File "/Users/katya/venv/lib/python2.7/site-packages/hyperopt-0.0.2-py2.7.egg/hyperopt/fmin.py", line 114, in evaluate
  File "run.py", line 35, in call_experiment
    feats_and_args, folds=num_folds)
  File "/Users/katya/repos/ARKcat/src/classify_test.py", line 66, in classify
    acc = m_and_d.k_fold_cv(folds)
  File "/Users/katya/repos/ARKcat/src/models_and_data.py", line 58, in k_fold_cv
    train_acc = self.train_models(self.train[0], self.train[1])
  File "/Users/katya/repos/ARKcat/src/models_and_data.py", line 102, in train_models
    train_X.append([vectorizer.transform(word) for word in example])
  File "/Users/katya/venv/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 1333, in transform
    X = super(TfidfVectorizer, self).transform(raw_documents)
  File "/Users/katya/venv/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 866, in transform
    _, X = self._count_vocab(raw_documents, fixed_vocab=True)
  File "/Users/katya/venv/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 752, in _count_vocab
    for feature in analyze(doc):
  File "/Users/katya/venv/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 238, in <lambda>
    tokenize(preprocess(self.decode(doc))), stop_words)
  File "/Users/katya/venv/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 115, in decode
    doc = doc.decode(self.encoding, self.decode_error)
  File "/Users/katya/venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 0: unexpected end of data
